config/routes.rb
Rails.application.routes.draw do
  root to: 'reports#index'
  devise_for :users
  resources :reports, only: [:index, :new, :create, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: :show 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :report, counter_cache: :likes_count
  belongs_to :user
  validates_uniqueness_of :report_id, scope: :user_id
end

app/models/report.rb
class Report < ApplicationRecord
  validates :checkbox, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :reports
  has_many :likes
  has_many :liked_reports, through: :likes, source: :report
  def already_liked?(report)
    self.likes.exists?(report_id: report.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  protect_from_forgery with: :exception
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(report_id: params[:report_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(report_id: params[:report_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    @user = User.all.includes(:reports).order("created_at DESC").page(params[:page]).per(12)
  end

  def new
    @report = Report.new 
  end

  def create
    Report.create(report_params)
    redirect_to controller: 'users', action: 'show', id:current_user.id
  end

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @report = user.reports.order("created_at DESC").page(params[:page]).per(5)
    @like = Like.new
  end

  private 
    def report_params
      params.require(:report).permit(:checkbox, :image).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @reports = @user.reports.order("created_at DESC").page(params[:page]).per(5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 家事レポ
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
  .header
    = link_to root_path, class:"header__left-box" do
      kaji-repo
    .header__right-box
      -if user_signed_in?
        = link_to user_path(current_user), class:"header__right-box__name" do
          = current_user.nickname
          さんの家事一覧
        = link_to new_report_path, class: "header__right-box__btn" do
          家事を投稿する
        = link_to destroy_user_session_path, method: :delete, class: "header__right-box__btn" do
          ログアウト
      -else 
        = link_to new_user_session_path, class: "header__right-box__btn" do
          ログイン
        = link_to new_user_registration_path, class: "header__right-box__btn" do
          新規登録
  %body
    = yield

app/views/likes/_like.html.haml
- if current_user.already_liked?(report)
  %label
    = icon('fas','heart',class: 'icon')
    .hidden
      = button_to "いいね済み", report_like_path(report_id: report.id), {method: "delete", remote: true}
- else
  %label
    = icon('far','heart',class: 'icon')
    .hidden
      = button_to 'いいね', report_likes_path(report)

app/views/reports/_form.html.haml
= form_for [report] do |f|
  .form__checkbox
    %label.form__checkbox__check
      .check
        = f.radio_button :checkbox, "洗濯" 
        洗濯
    %label
      .check
        = f.radio_button :checkbox, "掃除" 
        掃除
    %label
      .check
        = f.radio_button :checkbox, "料理"    
        料理
    %label
      .check
        = f.radio_button :checkbox, "買い物"  
        買い物
    %label
      .check
        = f.radio_button :checkbox, "洗い物"
        洗い物   
    %label
      = icon('fa','image',class: 'icon')
      写真
      .hidden
        = f.file_field :image
  .form__submit
    %input.form__submit__btn{type: 'submit', value: '家事を投稿！'}

app/views/reports/index.html.haml
.main
  .main__heading
    みんなの投稿
  .main__user
    - @user.each do |user|
      .main__user__list
        = link_to report_path(user.id), class:"main__user__list__btn" do
          = user.nickname 
        .main__user__report-count
          投稿数:
          = user.reports.count
        .main__user__like-count
          いいね:
          = user.likes.count
  .main__footer
    = paginate(@user)

app/views/reports/new.html.haml
.form
  .form__post
    投稿画面
    = render 'form', report: @report

app/views/reports/show.html.haml
.detail
  .detail__user-name
    = @nickname
    さんの投稿
  .detail__main
    - @report.each do |report|
      .detail__main__report
        .detail__main__report__left-box
          .detail__main__report__left-box__created-at
            = report.created_at.strftime("%Y-%m-%d %H:%M")
          .detail__main__report__left-box__like
          - if user_signed_in?
            = render 'likes/like', report: report
          - else
            = icon('far','heart',class: 'icon')
          .detail__main__report__left-box__like-count
            = report.likes.count
            いいね！
        .detail__main__report__right-box
          .detail__main__report__right-box__report
            = report.checkbox
            をやりました!
          .detail__main__report__right-box__image
            = image_tag report.image, class: 'main__contents__right',size: "350x200"
  .detail__fotter
    = paginate(@report)

app/views/users/show.html.haml
.detail
  .detail__fix
    .detail__fix__user-name
      = @user.nickname
      さんの投稿
      %br
      やり忘れはありませんか？
    .detail__fix__checkbox
      =check_box_tag :check1 
      = label_tag :check1, "洗濯"
      =check_box_tag :check2 
      = label_tag :check2, "掃除"
      =check_box_tag :check3 
      = label_tag :check3, "料理"
      =check_box_tag :check4 
      = label_tag :check4, "買い物"
      =check_box_tag :check5 
      = label_tag :check5, "洗い物"
  
  - @reports.each do |report|
    .detail__main-box
      .detail__mainbox__left-box
        .detail__mainbox__left-box__created-at
          = report.created_at.strftime("%Y-%m-%d %H:%M")
        .detail__mainbox__left-box__like
          いいね
          = report.likes_count
      .detail__mainbox__right-box
        .detail__mainbox__right-box__report
          = report.checkbox
          をやりました!
        .detail__mainbox__right-box__image
          = image_tag report.image, class: 'main__contents__right',size: "350x200"
  .detail__fotter
    = paginate(@reports)